### ISSUE TITLE
syntax errors 

### ISSUE THREAD

**Issue by aperez2001** [aws/aws-ops-wheel#26]
hey guys im trying to run this program for a project but i keep getting syntax errors does anybody know how to fix this? also i am new to python

**Comment by iulianmac** [comment]
Hello.

Can you provide a log with the errors you are getting? also the command you are running?

**Comment by trenton** [comment]
I recently encountered some test failures (fixed in https://github.com/aws/aws-ops-wheel/pull/36) but no syntax errors. The project requires Python 3... maybe you were using Python 2?

Vote to close.

**Comment by brandonjs** [comment]
Closing 3yo issue.
