### ISSUE TITLE
Add autoscaling to cloudformation template for Ops-wheel

### ISSUE THREAD

**Issue by z-stamboel** [aws/aws-ops-wheel#27]
Currently, the ops-wheel tables are not configured with auto-scaling. Requesting for it to be configured through the cloudformation with autoscaling to lower the cost of workloads that have a predictable traffic pattern.

Reference: https://aws.amazon.com/blogs/database/amazon-dynamodb-auto-scaling-performance-and-cost-optimization-at-any-scale/

**Comment by trenton** [comment]
Instead of auto scaling, this PR changes them to on demand, which is probably a better fit for a very lightly used app like this.

https://github.com/aws/aws-ops-wheel/pull/39

**Comment by brandonjs** [comment]
DDB tables are on-demand now in the template per #92.  Closing this issue as it's over 3 years old.
