### ISSUE TITLE
Not able to change password for any user

### ISSUE THREAD

**Issue by abhi788906** [aws/aws-ops-wheel#87]
Hi guys,

I just launched in us-west-2 to test the template. It was easy to deploy but not able to log in whenever I try to sign in with admin user it ask to change password as signin in first time and gives an error that cannot modify the email.

![image](https://user-images.githubusercontent.com/92846136/169269886-e7be36b3-7d3a-4e18-bf18-460d843a4f01.png)

**Comment by brandonjs** [comment]
Investigating. I've been able to validate this issue is happening in a stack I just launched. Looking into why this is happening.

**Comment by vineet-wustl** [comment]
Thanks!

**Comment by abhi788906** [comment]
Hi Brandonjs, In order to resolve this issue, we should have to change the code on the \"aws-ops-wheel\" application such that the application does not send \"userAttributes.email\" parameter while making \"RespondToAuthChallenge\" API call.

**Comment by iamrahularora** [comment]
@brandonjs: Password reset issue still persists after validation with updated code. Please look into it.
![image](https://user-images.githubusercontent.com/72094318/170241739-57cdcf32-7292-492d-b4ee-0a7dacef9e3b.png)

**Comment by brandonjs** [comment]
@iamrahularora How did you deploy/update the stack?  The code has been pushed, but the "one-click" launch template on the front page has not yet.  I am currently working on that.

**Comment by brandonjs** [comment]
one-click launch template has been updated.  Verified by launching a new stack and able to change the password.
