### ISSUE TITLE
Better support for long names of the Wheel's entries

### ISSUE THREAD

**Issue by shabo** [aws/aws-ops-wheel#9]
Currently, when the Wheel's owner enters a long name, it does not render nicely and can lead to a bad look of the wheel. It needs to have better rendering capabilities and also possibly provide a configuration allowing the user to customize the font size or the way the entry text is rendered in the Wheel.

**Comment by brandonjs** [comment]
Closing 4yo issue as it appears fixed by the PRs mentioned.
